### ISSUE TITLE
可以改善寫法的地方? idk

### ISSUE THREAD

**Issue by xiaoxigua-1** [IceLeiYu/OrderlyDiscordBot#3]
[這裡](https://github.com/IceLeiYu/OrderlyDiscordBot/blob/95b995f7f7ab211808fb0b065038d09929715e8d/src/main/java/command/CommandRegister.java#L49)
或許可以用printf 或 String.format 或 formatted 或 MessageFormat.format ?

**Comment by xiaoxigua-1** [comment]
[這裡是?](https://github.com/IceLeiYu/OrderlyDiscordBot/blob/95b995f7f7ab211808fb0b065038d09929715e8d/src/main/java/event/Log.java#L63)

**Comment by xiaoxigua-1** [comment]
分號好邊緣 QAQ [這裡](https://github.com/IceLeiYu/OrderlyDiscordBot/blob/95b995f7f7ab211808fb0b065038d09929715e8d/src/main/java/event/Log.java#L86)

**Comment by xiaoxigua-1** [comment]
> [這裡](https://github.com/IceLeiYu/OrderlyDiscordBot/blob/95b995f7f7ab211808fb0b065038d09929715e8d/src/main/java/command/CommandRegister.java#L49) 或許可以用printf 或 format ?

[皮諾可這個直接電死](https://github.com/IceLeiYu/OrderlyDiscordBot/blob/95b995f7f7ab211808fb0b065038d09929715e8d/src/main/java/ListenerManager.java#L367)

**Comment by IceLeiYu** [comment]
> [這裡是?](https://github.com/IceLeiYu/OrderlyDiscordBot/blob/95b995f7f7ab211808fb0b065038d09929715e8d/src/main/java/event/Log.java#L63)

`System.err.printf("[%s%n] Command Update Failed!", event.getGuild().getName());`

**Comment by IceLeiYu** [comment]
> > [這裡](https://github.com/IceLeiYu/OrderlyDiscordBot/blob/95b995f7f7ab211808fb0b065038d09929715e8d/src/main/java/command/CommandRegister.java#L49) 或許可以用printf 或 String.format 或 formatted 或 MessageFormat.format ?
> 
> [皮諾可這個直接電死](https://github.com/IceLeiYu/OrderlyDiscordBot/blob/95b995f7f7ab211808fb0b065038d09929715e8d/src/main/java/ListenerManager.java#L367)

給我點時間改全部的文件ww

**Comment by IceLeiYu** [comment]
> 分號好邊緣 QAQ [這裡](https://github.com/IceLeiYu/OrderlyDiscordBot/blob/95b995f7f7ab211808fb0b065038d09929715e8d/src/main/java/event/Log.java#L86)

塞回去ㄌ

**Comment by IceLeiYu** [comment]
> [這裡是?](https://github.com/IceLeiYu/OrderlyDiscordBot/blob/95b995f7f7ab211808fb0b065038d09929715e8d/src/main/java/event/Log.java#L63)

有什麼不對ㄇQWQ

**Comment by xiaoxigua-1** [comment]
> > [這裡是?](https://github.com/IceLeiYu/OrderlyDiscordBot/blob/95b995f7f7ab211808fb0b065038d09929715e8d/src/main/java/event/Log.java#L63)
> 
> 
> 
> 有什麼不對ㄇQWQ

逗號怎麼跑下來了

**Comment by IceLeiYu** [comment]
> > > [這裡是?](https://github.com/IceLeiYu/OrderlyDiscordBot/blob/95b995f7f7ab211808fb0b065038d09929715e8d/src/main/java/event/Log.java#L63)
> > 
> > 
> > 有什麼不對ㄇQWQ
> 
> 逗號怎麼跑下來了

喔杆!!!!!!!!!
